### ISSUE TITLE
Update content links to use Content Identifiers (CIDs)

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITK#3760]
### Description

Migrate data to IPFS and remove existing .md5 and .sha512 testing data content link identifiers and use .cid content link identifiers.

Since every local Git repository contains a copy of the entire project history, it is important to avoid adding large binary files directly to the repository. Large binary files added and removed throughout a project's history will cause the repository to become bloated, take up too much disk space, require excessive time and bandwidth to download, etc.

A solution to this problem which has been adopted by this project, is to store binary files such as images in a separate location outside the Git repository. Then, download the files at build time with CMake.

A "content link" file contains an identifying Content Identifier (CID). The content link is stored in the Git repository at the path where the file would exist, but with a .cid` extension appended to the file name. CMake will find these content link files at build time, download them from a list of server resources, and create symlinks or copies of the original files at the corresponding location in the build tree.

### Impact analysis

The Content Identifier (CID) is self-describing hash following the multiformats standard created by the Interplanetary Filesystem (IPFS) community. A file with a CID for its filename is content-verifable. Locating files according to their CID makes content-addressed, as opposed to location-addressed, data exchange possible. This practice is the foundation of the decentralized web, also known as the dWeb or Web3. By adopting Web3, we gain:

- Permissionless data uploads
- Robust, redundant storage
- Local and peer-to-peer storage
- Scalability
- Sustainability

### Expected behavior

Contributors to the examples upload their data through an easy-to-use, permissionless, free service, web3.storage.

Data used in the examples Git repository is periodically tracked in a dedicated Datalad repository and stored across redundant locations so it can be retrieved from any of the following:

- Local IPFS nodes
- Peer IPFS nodes
- web3.storage
- pinata.cloud
- Kitware's HTTP Server

### Actual behavior

We currently have to two content links to support two different hash types -- content identifiers naturally support multiple hash types via multiformats.

Contributing data storage support currently requires permissions.

We have limited redundancy. The process for uploading redundant data is difficult and time consuming.

We do not have testing data distributed in semantically meaningful file tree / file names.

Community members contributing testing data need to use a complicated, time consuming process.

Data management is an impediment to cutting timely releases.

### Versions

This updates are planned for ITK 5.4.0

### Additional Information

This is a follow up for the ITK repository what has already proven to work in itk-wasm / ITKSphinxExamples https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/pull/398

Steps:

1. [x] Migrate CID-enabled ExternalData.cmake into [its own repository](https://github.com/InsightSoftwareConsortium/CMakeIPFSExternalData) as a commonly updated resource.
2. [x] Integrate CID-enabled ExternalData.cmake into ITK - done via https://github.com/InsightSoftwareConsortium/ITK/commit/73e67962a11bdbe2bed75590130631a2f6d60387
3. [x] Migrate content links to .cid #4215 
4. [x] Distribute across redundant storage: web3.storage, pinata.cloud, gin.g-node.org, web.kitware.com, ITKTestingData gh-pages, local pins
5. [x] Create [DataLad ITK testing data repository](https://gin.g-node.org/InsightSoftwareConsortium/ITKData)
6. [x] Remove old content links #4215 
7. [x] Update developer documentation #4215
8. [x] Remove old content link infrastructure
9. [x] Update maintainer release testing data archive documentation #4336

**Comment by thewtex** [comment]
xref #3323

**Comment by thewtex** [comment]
Done
